"""empty message

Revision ID: d61d8a07aabe
Revises: 
Create Date: 2022-01-04 10:19:55.505311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61d8a07aabe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odss_away', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('home_wins', sa.Float(), nullable=True),
    sa.Column('home_draws', sa.Float(), nullable=True),
    sa.Column('home_losses', sa.Float(), nullable=True),
    sa.Column('home_goals', sa.Float(), nullable=True),
    sa.Column('home_shots', sa.Float(), nullable=True),
    sa.Column('home_shots_on_target', sa.Float(), nullable=True),
    sa.Column('home_opposition_goals', sa.Float(), nullable=True),
    sa.Column('home_opposition_shots', sa.Float(), nullable=True),
    sa.Column('home_opposition_shots_on_target', sa.Float(), nullable=True),
    sa.Column('away_wins', sa.Float(), nullable=True),
    sa.Column('away_draws', sa.Float(), nullable=True),
    sa.Column('away_losses', sa.Float(), nullable=True),
    sa.Column('away_goals', sa.Float(), nullable=True),
    sa.Column('away_shots', sa.Float(), nullable=True),
    sa.Column('away_shots_on_target', sa.Float(), nullable=True),
    sa.Column('away_opposition_goals', sa.Float(), nullable=True),
    sa.Column('away_opposition_shots', sa.Float(), nullable=True),
    sa.Column('away_opposition_shots_on_target', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
